# Generated by Django 3.2.5 on 2022-01-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='flowrate1',
            new_name='flowrate',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='flowrate2',
        ),
    ]
