# Generated by Django 3.2.5 on 2022-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ImageField(null=True, upload_to='attendance_pics'),
        ),
    ]
