# Generated by Django 3.2.5 on 2022-02-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20220130_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
