# Generated by Django 3.2.5 on 2022-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='mH',
            field=models.CharField(blank=True, default=80.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='command',
            name='mL',
            field=models.CharField(blank=True, default=30.0, max_length=10),
        ),
    ]
