# Generated by Django 3.2.5 on 2022-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20221128_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(null=True, upload_to='garden_pic')),
                ('height', models.CharField(max_length=150)),
                ('create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
