# Generated by Django 3.2.5 on 2022-11-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_imageheight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageHeight',
            new_name='Height',
        ),
    ]
