# Generated by Django 3.2.5 on 2022-11-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_rename_imageheight_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='height',
            name='height',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
