# Generated by Django 3.2.5 on 2023-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_height_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='updates')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('current_update', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='height',
            name='name',
            field=models.ImageField(null=True, upload_to='height'),
        ),
    ]
