# Generated by Django 3.2.5 on 2023-07-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20230716_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupdate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
