# Generated by Django 3.2.5 on 2023-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_fileupdate_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupdate',
            name='file',
            field=models.BinaryField(),
        ),
    ]
